"""Contribution + delta arithmetic (spec §19). These numbers are pure arithmetic over
stored features — never generated by an LLM.

``contribution(feature_i) = normalized_i * effective_weight_i``
``delta_contribution(feature_i) = new_contribution_i - old_contribution_i``  (vs prior snapshot)
"""

from __future__ import annotations

from typing import Any

_EPS = 1e-9


def build_delta_breakdown(
    current: dict[str, Any], previous: dict[str, Any] | None
) -> dict[str, Any]:
    """``current`` / ``previous`` are ``ScoreSnapshot.contribution_breakdown`` dicts.

    Shape:
      {"dimensions": {name: {"score": .., "weighted": .., "features": {fname: {...}}}},
       "priority": float}
    """
    prev = previous or {}
    prev_dims = prev.get("dimensions", {})
    cur_dims = current.get("dimensions", {})

    dim_deltas: dict[str, Any] = {}
    feature_deltas: list[dict[str, Any]] = []

    for dname, cdim in cur_dims.items():
        pdim = prev_dims.get(dname, {})
        d_score = _delta(cdim.get("score"), pdim.get("score"))
        d_weighted = _delta(cdim.get("weighted"), pdim.get("weighted"))
        cfeats = cdim.get("features", {})
        pfeats = pdim.get("features", {})
        fdelta: dict[str, Any] = {}
        for fname, cf in cfeats.items():
            pf = pfeats.get(fname, {})
            old_c = pf.get("contribution", 0.0) or 0.0
            new_c = cf.get("contribution", 0.0) or 0.0
            delta = round(new_c - old_c, 4)
            fdelta[fname] = {
                "old": round(old_c, 4),
                "new": round(new_c, 4),
                "delta": delta,
                "old_normalized": pf.get("normalized"),
                "new_normalized": cf.get("normalized"),
                "old_status": pf.get("status"),
                "new_status": cf.get("status"),
            }
            if abs(delta) > 1e-4:
                feature_deltas.append(
                    {"dimension": dname, "feature": fname, "delta": delta, **fdelta[fname]}
                )
        dim_deltas[dname] = {
            "score_delta": d_score,
            "weighted_delta": d_weighted,
            "features": fdelta,
        }

    feature_deltas.sort(key=lambda d: abs(d["delta"]), reverse=True)
    return {
        "priority_delta": _delta(current.get("priority"), prev.get("priority")),
        "dimensions": dim_deltas,
        "top_movers": feature_deltas[:12],
    }


def _delta(new: float | None, old: float | None) -> float | None:
    if new is None:
        return None
    return round(new - (old or 0.0), 4)


def summarize_movers(delta_breakdown: dict[str, Any], limit: int = 5) -> list[str]:
    """Human-readable driver lines (deterministic; used by the digest)."""
    lines: list[str] = []
    for mover in delta_breakdown.get("top_movers", [])[:limit]:
        sign = "+" if mover["delta"] >= 0 else ""
        lines.append(f"{sign}{mover['delta']:.1f} {mover['dimension']}: {mover['feature']}")
    return lines
