"""initial schema

Revision ID: 2827d9120b33
Revises:
Create Date: 2026-09-03 23:02:23.281310

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

import intelligence.types  # custom column types (GUID / JSONB / UTCDateTime) used across the schema


revision: str = "2827d9120b33"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "action_rule_set",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("rules", intelligence.types.JSONB(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("activated_at", intelligence.types.UTCDateTime(), nullable=True),
        sa.Column("id", intelligence.types.GUID(), nullable=False),
        sa.Column(
            "created_at",
            intelligence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "version", name="uq_action_rule_set_name_version"),
    )
    with op.batch_alter_table("action_rule_set", schema=None) as batch_op:
        batch_op.create_index("ix_action_rule_set_status", ["status"], unique=False)

    op.create_table(
        "discovery_rule",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("target_class", sa.String(length=32), nullable=False),
        sa.Column("industries", intelligence.types.JSONB(), nullable=False),
        sa.Column("technical_topics", intelligence.types.JSONB(), nullable=False),
        sa.Column("titles", intelligence.types.JSONB(), nullable=False),
        sa.Column("prior_employers", intelligence.types.JSONB(), nullable=False),
        sa.Column("geographies", intelligence.types.JSONB(), nullable=False),
        sa.Column("keywords", intelligence.types.JSONB(), nullable=False),
        sa.Column("excluded_keywords", intelligence.types.JSONB(), nullable=False),
        sa.Column("source_ids", intelligence.types.JSONB(), nullable=False),
        sa.Column("lookback_days", sa.Integer(), nullable=False),
        sa.Column("minimum_evidence", intelligence.types.JSONB(), nullable=False),
        sa.Column("created_by", sa.String(length=120), nullable=False),
        sa.Column("id", intelligence.types.GUID(), nullable=False),
        sa.Column(
            "created_at",
            intelligence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            intelligence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "entity_resolution_result",
        sa.Column("candidate_observation_id", intelligence.types.GUID(), nullable=True),
        sa.Column("candidate_person_id", intelligence.types.GUID(), nullable=True),
        sa.Column("matched_person_id", intelligence.types.GUID(), nullable=True),
        sa.Column("decision", sa.String(length=24), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("scorecard", intelligence.types.JSONB(), nullable=False),
        sa.Column("competing_person_ids", intelligence.types.JSONB(), nullable=False),
        sa.Column("auto_applied", sa.Boolean(), nullable=False),
        sa.Column("reviewed", sa.Boolean(), nullable=False),
        sa.Column("reviewer_user_id", sa.String(length=120), nullable=True),
        sa.Column("id", intelligence.types.GUID(), nullable=False),
        sa.Column(
            "created_at",
            intelligence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "fact",
        sa.Column("subject_type", sa.String(length=24), nullable=False),
        sa.Column("subject_id", intelligence.types.GUID(), nullable=False),
        sa.Column("fact_type", sa.String(length=64), nullable=False),
        sa.Column("structured_value", intelligence.types.JSONB(), nullable=False),
        sa.Column("valid_from", intelligence.types.UTCDateTime(), nullable=True),
        sa.Column("valid_to", intelligence.types.UTCDateTime(), nullable=True),
        sa.Column("extraction_method", sa.String(length=32), nullable=False),
        sa.Column("extraction_confidence", sa.Float(), nullable=True),
        sa.Column("extractor_version", sa.String(length=64), nullable=False),
        sa.Column("superseded_by_id", intelligence.types.GUID(), nullable=True),
        sa.Column("id", intelligence.types.GUID(), nullable=False),
        sa.Column(
            "created_at",
            intelligence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["superseded_by_id"], ["fact.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("fact", schema=None) as batch_op:
        batch_op.create_index(
            "ix_fact_subject", ["subject_type", "subject_id", "fact_type"], unique=False
        )

    op.create_table(
        "organization",
        sa.Column("canonical_name", sa.String(length=255), nullable=False),
        sa.Column("organization_type", sa.String(length=32), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("founding_date", sa.Date(), nullable=True),
        sa.Column("aum_usd", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("is_portfolio", sa.Boolean(), nullable=False),
        sa.Column("attributes", intelligence.types.JSONB(), nullable=False),
        sa.Column("id", intelligence.types.GUID(), nullable=False),
        sa.Column(
            "created_at",
            intelligence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            intelligence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("organization", schema=None) as batch_op:
        batch_op.create_index("ix_organization_domain", ["domain"], unique=False)
        batch_op.create_index("ix_organization_name", ["canonical_name"], unique=False)

    op.create_table(
        "scoring_model",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("target_class", sa.String(length=16), nullable=False),
        sa.Column("configuration", intelligence.types.JSONB(), nullable=False),
        sa.Column("config_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("activated_at", intelligence.types.UTCDateTime(), nullable=True),
        sa.Column("retired_at", intelligence.types.UTCDateTime(), nullable=True),
        sa.Column("id", intelligence.types.GUID(), nullable=False),
        sa.Column(
            "created_at",
            intelligence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "version", name="uq_scoring_model_name_version"),
    )
    with op.batch_alter_table("scoring_model", schema=None) as batch_op:
        batch_op.create_index("ix_scoring_model_name", ["name"], unique=False)

    op.create_table(
        "source",
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("provider", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("reliability_tier", sa.SmallInteger(), nullable=False),
        sa.Column("configuration", intelligence.types.JSONB(), nullable=False),
        sa.Column("last_successful_run", intelligence.types.UTCDateTime(), nullable=True),
        sa.Column("id", intelligence.types.GUID(), nullable=False),
        sa.Column(
            "created_at",
            intelligence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "story_cluster",
        sa.Column("cluster_key", sa.String(length=255), nullable=False),
        sa.Column("canonical_url", sa.String(length=1024), nullable=True),
        sa.Column("first_seen_at", intelligence.types.UTCDateTime(), nullable=True),
        sa.Column("article_count", sa.Integer(), nullable=False),
        sa.Column("distinct_domain_count", sa.Integer(), nullable=False),
        sa.Column("id", intelligence.types.GUID(), nullable=False),
        sa.Column(
            "created_at",
            intelligence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("story_cluster", schema=None) as batch_op:
        batch_op.create_index("ix_story_cluster_key", ["cluster_key"], unique=False)

    op.create_table(
        "thesis_configuration",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("is_sample", sa.Boolean(), nullable=False),
        sa.Column("sectors", intelligence.types.JSONB(), nullable=False),
        sa.Column("technologies", intelligence.types.JSONB(), nullable=False),
        sa.Column("business_models", intelligence.types.JSONB(), nullable=False),
        sa.Column("stages", intelligence.types.JSONB(), nullable=False),
        sa.Column("geographies", intelligence.types.JSONB(), nullable=False),
        sa.Column("technical_topics", intelligence.types.JSONB(), nullable=False),
        sa.Column("embedding_model", sa.String(length=120), nullable=True),
        sa.Column("embedding_model_version", sa.String(length=64), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", intelligence.types.GUID(), nullable=False),
        sa.Column(
            "created_at",
            intelligence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "version", name="uq_thesis_name_version"),
    )
    op.create_table(
        "weekly_run",
        sa.Column("started_at", intelligence.types.UTCDateTime(), nullable=False),
        sa.Column("finished_at", intelligence.types.UTCDateTime(), nullable=True),
        sa.Column("as_of_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("source_coverage", intelligence.types.JSONB(), nullable=False),
        sa.Column("observations_ingested", sa.Integer(), nullable=False),
        sa.Column("people_updated", sa.Integer(), nullable=False),
        sa.Column("people_discovered", sa.Integer(), nullable=False),
        sa.Column("facts_created", sa.Integer(), nullable=False),
        sa.Column("events_created", sa.Integer(), nullable=False),
        sa.Column("inferences_created", sa.Integer(), nullable=False),
        sa.Column("scoring_models_run", intelligence.types.JSONB(), nullable=False),
        sa.Column("stage_stats", intelligence.types.JSONB(), nullable=False),
        sa.Column("errors", intelligence.types.JSONB(), nullable=False),
        sa.Column("warnings", intelligence.types.JSONB(), nullable=False),
        sa.Column("code_version", sa.String(length=64), nullable=False),
        sa.Column("config_version", sa.String(length=64), nullable=False),
        sa.Column("digest", intelligence.types.JSONB(), nullable=True),
        sa.Column("id", intelligence.types.GUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("weekly_run", schema=None) as batch_op:
        batch_op.create_index("ix_weekly_run_started", ["started_at"], unique=False)

    op.create_table(
        "entity_merge_log",
        sa.Column("winner_person_id", intelligence.types.GUID(), nullable=False),
        sa.Column("loser_person_id", intelligence.types.GUID(), nullable=False),
        sa.Column("decision_source", sa.String(length=16), nullable=False),
        sa.Column("resolution_result_id", intelligence.types.GUID(), nullable=True),
        sa.Column("merged_fields", intelligence.types.JSONB(), nullable=False),
        sa.Column("analyst_user_id", sa.String(length=120), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("reverted_at", intelligence.types.UTCDateTime(), nullable=True),
        sa.Column("id", intelligence.types.GUID(), nullable=False),
        sa.Column(
            "created_at",
            intelligence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["resolution_result_id"], ["entity_resolution_result.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("entity_merge_log", schema=None) as batch_op:
        batch_op.create_index("ix_merge_loser", ["loser_person_id"], unique=False)
        batch_op.create_index("ix_merge_winner", ["winner_person_id"], unique=False)

    op.create_table(
        "person",
        sa.Column("canonical_name", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=120), nullable=True),
        sa.Column("last_name", sa.String(length=120), nullable=True),
        sa.Column("primary_location", sa.String(length=255), nullable=True),
        sa.Column("primary_email", sa.String(length=320), nullable=True),
        sa.Column("primary_linkedin_url", sa.String(length=512), nullable=True),
        sa.Column("current_title", sa.String(length=255), nullable=True),
        sa.Column("current_organization_id", intelligence.types.GUID(), nullable=True),
        sa.Column("monitoring_status", sa.String(length=32), nullable=False),
        sa.Column("entity_resolution_status", sa.String(length=32), nullable=False),
        sa.Column("entity_resolution_confidence", sa.Float(), nullable=True),
        sa.Column("merged_into_id", intelligence.types.GUID(), nullable=True),
        sa.Column("is_chimera_seed", sa.Boolean(), nullable=False),
        sa.Column("pinned", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("first_seen_at", intelligence.types.UTCDateTime(), nullable=True),
        sa.Column("last_observed_at", intelligence.types.UTCDateTime(), nullable=True),
        sa.Column("id", intelligence.types.GUID(), nullable=False),
        sa.Column(
            "created_at",
            intelligence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            intelligence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["current_organization_id"], ["organization.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["merged_into_id"], ["person.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("person", schema=None) as batch_op:
        batch_op.create_index("ix_person_canonical_name", ["canonical_name"], unique=False)
        batch_op.create_index("ix_person_email", ["primary_email"], unique=False)
        batch_op.create_index("ix_person_linkedin", ["primary_linkedin_url"], unique=False)

    op.create_table(
        "portfolio_role_need",
        sa.Column("portfolio_company_id", intelligence.types.GUID(), nullable=False),
        sa.Column("role_title", sa.String(length=200), nullable=False),
        sa.Column("function", sa.String(length=32), nullable=False),
        sa.Column("seniority", sa.String(length=32), nullable=False),
        sa.Column("domain_requirements", intelligence.types.JSONB(), nullable=False),
        sa.Column("stage_requirements", intelligence.types.JSONB(), nullable=False),
        sa.Column("location_requirements", intelligence.types.JSONB(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("id", intelligence.types.GUID(), nullable=False),
        sa.Column(
            "created_at",
            intelligence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            intelligence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["portfolio_company_id"], ["organization.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("portfolio_role_need", schema=None) as batch_op:
        batch_op.create_index("ix_role_need_company", ["portfolio_company_id"], unique=False)

    op.create_table(
        "ranking_universe",
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("model_target", sa.String(length=16), nullable=False),
        sa.Column("scoring_model_id", intelligence.types.GUID(), nullable=True),
        sa.Column("filter", intelligence.types.JSONB(), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=True),
        sa.Column("member_count", sa.Integer(), nullable=False),
        sa.Column("id", intelligence.types.GUID(), nullable=False),
        sa.Column(
            "created_at",
            intelligence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["scoring_model_id"], ["scoring_model.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "raw_observation",
        sa.Column("source_id", intelligence.types.GUID(), nullable=False),
        sa.Column("provider_record_id", sa.String(length=255), nullable=True),
        sa.Column("subject_hint", sa.String(length=255), nullable=True),
        sa.Column("occurred_at", intelligence.types.UTCDateTime(), nullable=True),
        sa.Column("observed_at", intelligence.types.UTCDateTime(), nullable=False),
        sa.Column("ingested_at", intelligence.types.UTCDateTime(), nullable=False),
        sa.Column("processed_at", intelligence.types.UTCDateTime(), nullable=True),
        sa.Column("source_url", sa.String(length=1024), nullable=True),
        sa.Column("content_type", sa.String(length=32), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=True),
        sa.Column("raw_json", intelligence.types.JSONB(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("story_cluster_id", intelligence.types.GUID(), nullable=True),
        sa.Column("metadata", intelligence.types.JSONB(), nullable=False),
        sa.Column("id", intelligence.types.GUID(), nullable=False),
        sa.ForeignKeyConstraint(["source_id"], ["source.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["story_cluster_id"], ["story_cluster.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("raw_observation", schema=None) as batch_op:
        batch_op.create_index("ix_raw_observation_hash", ["content_hash"], unique=False)
        batch_op.create_index(
            "ix_raw_observation_provider", ["source_id", "provider_record_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_raw_observation_source_id"), ["source_id"], unique=False
        )

    op.create_table(
        "analyst_override",
        sa.Column("target_type", sa.String(length=32), nullable=False),
        sa.Column("target_id", intelligence.types.GUID(), nullable=True),
        sa.Column("person_id", intelligence.types.GUID(), nullable=True),
        sa.Column("original_value", intelligence.types.JSONB(), nullable=True),
        sa.Column("override_value", intelligence.types.JSONB(), nullable=True),
        sa.Column("analyst_user_id", sa.String(length=120), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("reverted_at", intelligence.types.UTCDateTime(), nullable=True),
        sa.Column("id", intelligence.types.GUID(), nullable=False),
        sa.Column(
            "created_at",
            intelligence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["person_id"], ["person.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("analyst_override", schema=None) as batch_op:
        batch_op.create_index("ix_override_person", ["person_id"], unique=False)

    op.create_table(
        "candidate_role_match",
        sa.Column("person_id", intelligence.types.GUID(), nullable=False),
        sa.Column("portfolio_role_need_id", intelligence.types.GUID(), nullable=False),
        sa.Column("model_version", sa.String(length=32), nullable=False),
        sa.Column("calculated_at", intelligence.types.UTCDateTime(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("score_breakdown", intelligence.types.JSONB(), nullable=False),
        sa.Column("id", intelligence.types.GUID(), nullable=False),
        sa.Column(
            "created_at",
            intelligence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["person_id"], ["person.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["portfolio_role_need_id"], ["portfolio_role_need.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "person_id", "portfolio_role_need_id", "model_version", name="uq_candidate_role_model"
        ),
    )
    with op.batch_alter_table("candidate_role_match", schema=None) as batch_op:
        batch_op.create_index("ix_crm_person", ["person_id"], unique=False)
        batch_op.create_index("ix_crm_role", ["portfolio_role_need_id"], unique=False)

    op.create_table(
        "discovery_candidate",
        sa.Column("discovery_rule_id", intelligence.types.GUID(), nullable=False),
        sa.Column("person_id", intelligence.types.GUID(), nullable=True),
        sa.Column("first_discovered_at", intelligence.types.UTCDateTime(), nullable=False),
        sa.Column("source_id", intelligence.types.GUID(), nullable=True),
        sa.Column("triggering_evidence_ids", intelligence.types.JSONB(), nullable=False),
        sa.Column("identity_confidence", sa.Float(), nullable=False),
        sa.Column("candidate_classification", sa.String(length=32), nullable=False),
        sa.Column("promoted_to_person_id", intelligence.types.GUID(), nullable=True),
        sa.Column("promoted_at", intelligence.types.UTCDateTime(), nullable=True),
        sa.Column("dismissed", sa.Boolean(), nullable=False),
        sa.Column("dismissed_reason", sa.Text(), nullable=True),
        sa.Column("false_positive", sa.Boolean(), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("score_breakdown", intelligence.types.JSONB(), nullable=True),
        sa.Column("id", intelligence.types.GUID(), nullable=False),
        sa.Column(
            "created_at",
            intelligence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            intelligence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["discovery_rule_id"], ["discovery_rule.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["person_id"], ["person.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["promoted_to_person_id"], ["person.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_id"], ["source.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("discovery_candidate", schema=None) as batch_op:
        batch_op.create_index("ix_discovery_candidate_rule", ["discovery_rule_id"], unique=False)

    op.create_table(
        "education",
        sa.Column("person_id", intelligence.types.GUID(), nullable=False),
        sa.Column("institution_id", intelligence.types.GUID(), nullable=True),
        sa.Column("institution_name_raw", sa.String(length=255), nullable=True),
        sa.Column("degree", sa.String(length=120), nullable=True),
        sa.Column("field", sa.String(length=160), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("evidence_ids", intelligence.types.JSONB(), nullable=False),
        sa.Column("id", intelligence.types.GUID(), nullable=False),
        sa.Column(
            "created_at",
            intelligence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["institution_id"], ["organization.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["person_id"], ["person.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("education", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_education_person_id"), ["person_id"], unique=False)

    op.create_table(
        "employment",
        sa.Column("person_id", intelligence.types.GUID(), nullable=False),
        sa.Column("organization_id", intelligence.types.GUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("normalized_title", sa.String(length=255), nullable=True),
        sa.Column("function", sa.String(length=32), nullable=True),
        sa.Column("seniority", sa.String(length=32), nullable=True),
        sa.Column("started_at", sa.Date(), nullable=True),
        sa.Column("ended_at", sa.Date(), nullable=True),
        sa.Column("current", sa.Boolean(), nullable=False),
        sa.Column("evidence_ids", intelligence.types.JSONB(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("superseded_by_id", intelligence.types.GUID(), nullable=True),
        sa.Column("last_verified_at", intelligence.types.UTCDateTime(), nullable=True),
        sa.Column("id", intelligence.types.GUID(), nullable=False),
        sa.Column(
            "created_at",
            intelligence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            intelligence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organization.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["person_id"], ["person.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["superseded_by_id"], ["employment.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("employment", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_employment_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(
            "ix_employment_person_current", ["person_id", "current"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_employment_person_id"), ["person_id"], unique=False)

    op.create_table(
        "event",
        sa.Column("person_id", intelligence.types.GUID(), nullable=False),
        sa.Column("organization_id", intelligence.types.GUID(), nullable=True),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("occurred_at", intelligence.types.UTCDateTime(), nullable=True),
        sa.Column("detected_at", intelligence.types.UTCDateTime(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("evidence_ids", intelligence.types.JSONB(), nullable=False),
        sa.Column("structured_payload", intelligence.types.JSONB(), nullable=False),
        sa.Column("supersedes_event_id", intelligence.types.GUID(), nullable=True),
        sa.Column("dedupe_key", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("weekly_run_id", intelligence.types.GUID(), nullable=True),
        sa.Column("id", intelligence.types.GUID(), nullable=False),
        sa.Column(
            "created_at",
            intelligence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organization.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["person_id"], ["person.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["supersedes_event_id"], ["event.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["weekly_run_id"], ["weekly_run.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("event", schema=None) as batch_op:
        batch_op.create_index("ix_event_dedupe", ["dedupe_key"], unique=False)
        batch_op.create_index(
            "ix_event_person_occurred", ["person_id", "occurred_at"], unique=False
        )
        batch_op.create_index("ix_event_type", ["event_type"], unique=False)

    op.create_table(
        "evidence",
        sa.Column("fact_id", intelligence.types.GUID(), nullable=True),
        sa.Column("observation_id", intelligence.types.GUID(), nullable=False),
        sa.Column("source_url", sa.String(length=1024), nullable=True),
        sa.Column("source_label", sa.String(length=255), nullable=False),
        sa.Column("quoted_fragment", sa.Text(), nullable=True),
        sa.Column("observed_at", intelligence.types.UTCDateTime(), nullable=True),
        sa.Column("evidence_strength", sa.Float(), nullable=False),
        sa.Column("id", intelligence.types.GUID(), nullable=False),
        sa.Column(
            "created_at",
            intelligence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["fact_id"], ["fact.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["observation_id"], ["raw_observation.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("evidence", schema=None) as batch_op:
        batch_op.create_index("ix_evidence_fact", ["fact_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_evidence_observation_id"), ["observation_id"], unique=False
        )

    op.create_table(
        "extraction_run",
        sa.Column("observation_id", intelligence.types.GUID(), nullable=False),
        sa.Column("extractor_name", sa.String(length=64), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column("input_observation_ids", intelligence.types.JSONB(), nullable=False),
        sa.Column("output", intelligence.types.JSONB(), nullable=True),
        sa.Column("parse_status", sa.String(length=24), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("token_usage", intelligence.types.JSONB(), nullable=True),
        sa.Column("id", intelligence.types.GUID(), nullable=False),
        sa.Column(
            "created_at",
            intelligence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["observation_id"], ["raw_observation.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("extraction_run", schema=None) as batch_op:
        batch_op.create_index("ix_extraction_run_obs", ["observation_id"], unique=False)

    op.create_table(
        "inference",
        sa.Column("person_id", intelligence.types.GUID(), nullable=False),
        sa.Column("inference_type", sa.String(length=64), nullable=False),
        sa.Column("probability", sa.Float(), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column("evidence_ids", intelligence.types.JSONB(), nullable=False),
        sa.Column("explanation_code", sa.String(length=64), nullable=False),
        sa.Column("expires_at", intelligence.types.UTCDateTime(), nullable=True),
        sa.Column("id", intelligence.types.GUID(), nullable=False),
        sa.Column(
            "created_at",
            intelligence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["person_id"], ["person.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("inference", schema=None) as batch_op:
        batch_op.create_index(
            "ix_inference_person_type", ["person_id", "inference_type"], unique=False
        )

    op.create_table(
        "person_alias",
        sa.Column("person_id", intelligence.types.GUID(), nullable=False),
        sa.Column("alias_type", sa.String(length=32), nullable=False),
        sa.Column("alias_value", sa.String(length=512), nullable=False),
        sa.Column("source_id", intelligence.types.GUID(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("id", intelligence.types.GUID(), nullable=False),
        sa.Column(
            "created_at",
            intelligence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["person_id"], ["person.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_id"], ["source.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("person_alias", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_person_alias_person_id"), ["person_id"], unique=False)
        batch_op.create_index("ix_person_alias_value", ["alias_value"], unique=False)

    op.create_table(
        "person_classification",
        sa.Column("person_id", intelligence.types.GUID(), nullable=False),
        sa.Column("person_class", sa.String(length=32), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("assigned_by", sa.String(length=120), nullable=True),
        sa.Column("rationale_code", sa.String(length=64), nullable=True),
        sa.Column("id", intelligence.types.GUID(), nullable=False),
        sa.Column(
            "created_at",
            intelligence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["person_id"], ["person.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("person_id", "person_class", name="uq_person_class"),
    )
    with op.batch_alter_table("person_classification", schema=None) as batch_op:
        batch_op.create_index("ix_person_classification_person", ["person_id"], unique=False)

    op.create_table(
        "person_feature_snapshot",
        sa.Column("person_id", intelligence.types.GUID(), nullable=False),
        sa.Column("model_target", sa.String(length=16), nullable=False),
        sa.Column("feature_set_version", sa.String(length=32), nullable=False),
        sa.Column("calculated_at", intelligence.types.UTCDateTime(), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=True),
        sa.Column("features", intelligence.types.JSONB(), nullable=False),
        sa.Column("missing_features", intelligence.types.JSONB(), nullable=False),
        sa.Column("data_freshness", intelligence.types.JSONB(), nullable=False),
        sa.Column("id", intelligence.types.GUID(), nullable=False),
        sa.Column(
            "created_at",
            intelligence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["person_id"], ["person.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("person_feature_snapshot", schema=None) as batch_op:
        batch_op.create_index("ix_pfs_person_calc", ["person_id", "calculated_at"], unique=False)

    op.create_table(
        "relationship_edge",
        sa.Column("source_person_id", intelligence.types.GUID(), nullable=False),
        sa.Column("target_person_id", intelligence.types.GUID(), nullable=False),
        sa.Column("relationship_type", sa.String(length=32), nullable=False),
        sa.Column("relationship_strength", sa.String(length=16), nullable=False),
        sa.Column("strength_numeric", sa.Float(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("first_seen_at", intelligence.types.UTCDateTime(), nullable=True),
        sa.Column("last_verified_at", intelligence.types.UTCDateTime(), nullable=True),
        sa.Column("evidence_ids", intelligence.types.JSONB(), nullable=False),
        sa.Column("id", intelligence.types.GUID(), nullable=False),
        sa.Column(
            "created_at",
            intelligence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            intelligence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["source_person_id"], ["person.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_person_id"], ["person.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("relationship_edge", schema=None) as batch_op:
        batch_op.create_index("ix_edge_source", ["source_person_id"], unique=False)
        batch_op.create_index("ix_edge_target", ["target_person_id"], unique=False)

    op.create_table(
        "score_snapshot",
        sa.Column("person_id", intelligence.types.GUID(), nullable=False),
        sa.Column("scoring_model_id", intelligence.types.GUID(), nullable=False),
        sa.Column("feature_snapshot_id", intelligence.types.GUID(), nullable=True),
        sa.Column("weekly_run_id", intelligence.types.GUID(), nullable=True),
        sa.Column("scored_at", intelligence.types.UTCDateTime(), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=True),
        sa.Column("quality_score", sa.Float(), nullable=True),
        sa.Column("fit_score", sa.Float(), nullable=True),
        sa.Column("timing_score", sa.Float(), nullable=True),
        sa.Column("access_score", sa.Float(), nullable=True),
        sa.Column("priority_score", sa.Float(), nullable=False),
        sa.Column("confidence_score", sa.Float(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.Column("percentile", sa.Float(), nullable=True),
        sa.Column("rank_universe_id", intelligence.types.GUID(), nullable=True),
        sa.Column("previous_score_snapshot_id", intelligence.types.GUID(), nullable=True),
        sa.Column("contribution_breakdown", intelligence.types.JSONB(), nullable=False),
        sa.Column("delta_breakdown", intelligence.types.JSONB(), nullable=True),
        sa.Column("action", sa.String(length=32), nullable=True),
        sa.Column("reason_codes", intelligence.types.JSONB(), nullable=False),
        sa.Column("id", intelligence.types.GUID(), nullable=False),
        sa.Column(
            "created_at",
            intelligence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["feature_snapshot_id"], ["person_feature_snapshot.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["person_id"], ["person.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["previous_score_snapshot_id"], ["score_snapshot.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["rank_universe_id"], ["ranking_universe.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["scoring_model_id"], ["scoring_model.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["weekly_run_id"], ["weekly_run.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("score_snapshot", schema=None) as batch_op:
        batch_op.create_index(
            "ix_score_snapshot_lookup", ["person_id", "scoring_model_id", "scored_at"], unique=False
        )

    op.create_table(
        "analyst_feedback",
        sa.Column("person_id", intelligence.types.GUID(), nullable=False),
        sa.Column("user_id", sa.String(length=120), nullable=False),
        sa.Column("score_snapshot_id", intelligence.types.GUID(), nullable=True),
        sa.Column("feedback_type", sa.String(length=32), nullable=False),
        sa.Column("feedback_value", intelligence.types.JSONB(), nullable=True),
        sa.Column("reason_code", sa.String(length=64), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("connector_person_id", intelligence.types.GUID(), nullable=True),
        sa.Column("id", intelligence.types.GUID(), nullable=False),
        sa.Column(
            "created_at",
            intelligence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["connector_person_id"], ["person.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["person_id"], ["person.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["score_snapshot_id"], ["score_snapshot.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("analyst_feedback", schema=None) as batch_op:
        batch_op.create_index("ix_feedback_person", ["person_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("analyst_feedback", schema=None) as batch_op:
        batch_op.drop_index("ix_feedback_person")

    op.drop_table("analyst_feedback")
    with op.batch_alter_table("score_snapshot", schema=None) as batch_op:
        batch_op.drop_index("ix_score_snapshot_lookup")

    op.drop_table("score_snapshot")
    with op.batch_alter_table("relationship_edge", schema=None) as batch_op:
        batch_op.drop_index("ix_edge_target")
        batch_op.drop_index("ix_edge_source")

    op.drop_table("relationship_edge")
    with op.batch_alter_table("person_feature_snapshot", schema=None) as batch_op:
        batch_op.drop_index("ix_pfs_person_calc")

    op.drop_table("person_feature_snapshot")
    with op.batch_alter_table("person_classification", schema=None) as batch_op:
        batch_op.drop_index("ix_person_classification_person")

    op.drop_table("person_classification")
    with op.batch_alter_table("person_alias", schema=None) as batch_op:
        batch_op.drop_index("ix_person_alias_value")
        batch_op.drop_index(batch_op.f("ix_person_alias_person_id"))

    op.drop_table("person_alias")
    with op.batch_alter_table("inference", schema=None) as batch_op:
        batch_op.drop_index("ix_inference_person_type")

    op.drop_table("inference")
    with op.batch_alter_table("extraction_run", schema=None) as batch_op:
        batch_op.drop_index("ix_extraction_run_obs")

    op.drop_table("extraction_run")
    with op.batch_alter_table("evidence", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_evidence_observation_id"))
        batch_op.drop_index("ix_evidence_fact")

    op.drop_table("evidence")
    with op.batch_alter_table("event", schema=None) as batch_op:
        batch_op.drop_index("ix_event_type")
        batch_op.drop_index("ix_event_person_occurred")
        batch_op.drop_index("ix_event_dedupe")

    op.drop_table("event")
    with op.batch_alter_table("employment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_employment_person_id"))
        batch_op.drop_index("ix_employment_person_current")
        batch_op.drop_index(batch_op.f("ix_employment_organization_id"))

    op.drop_table("employment")
    with op.batch_alter_table("education", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_education_person_id"))

    op.drop_table("education")
    with op.batch_alter_table("discovery_candidate", schema=None) as batch_op:
        batch_op.drop_index("ix_discovery_candidate_rule")

    op.drop_table("discovery_candidate")
    with op.batch_alter_table("candidate_role_match", schema=None) as batch_op:
        batch_op.drop_index("ix_crm_role")
        batch_op.drop_index("ix_crm_person")

    op.drop_table("candidate_role_match")
    with op.batch_alter_table("analyst_override", schema=None) as batch_op:
        batch_op.drop_index("ix_override_person")

    op.drop_table("analyst_override")
    with op.batch_alter_table("raw_observation", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_raw_observation_source_id"))
        batch_op.drop_index("ix_raw_observation_provider")
        batch_op.drop_index("ix_raw_observation_hash")

    op.drop_table("raw_observation")
    op.drop_table("ranking_universe")
    with op.batch_alter_table("portfolio_role_need", schema=None) as batch_op:
        batch_op.drop_index("ix_role_need_company")

    op.drop_table("portfolio_role_need")
    with op.batch_alter_table("person", schema=None) as batch_op:
        batch_op.drop_index("ix_person_linkedin")
        batch_op.drop_index("ix_person_email")
        batch_op.drop_index("ix_person_canonical_name")

    op.drop_table("person")
    with op.batch_alter_table("entity_merge_log", schema=None) as batch_op:
        batch_op.drop_index("ix_merge_winner")
        batch_op.drop_index("ix_merge_loser")

    op.drop_table("entity_merge_log")
    with op.batch_alter_table("weekly_run", schema=None) as batch_op:
        batch_op.drop_index("ix_weekly_run_started")

    op.drop_table("weekly_run")
    op.drop_table("thesis_configuration")
    with op.batch_alter_table("story_cluster", schema=None) as batch_op:
        batch_op.drop_index("ix_story_cluster_key")

    op.drop_table("story_cluster")
    op.drop_table("source")
    with op.batch_alter_table("scoring_model", schema=None) as batch_op:
        batch_op.drop_index("ix_scoring_model_name")

    op.drop_table("scoring_model")
    with op.batch_alter_table("organization", schema=None) as batch_op:
        batch_op.drop_index("ix_organization_name")
        batch_op.drop_index("ix_organization_domain")

    op.drop_table("organization")
    with op.batch_alter_table("fact", schema=None) as batch_op:
        batch_op.drop_index("ix_fact_subject")

    op.drop_table("fact")
    op.drop_table("entity_resolution_result")
    op.drop_table("discovery_rule")
    with op.batch_alter_table("action_rule_set", schema=None) as batch_op:
        batch_op.drop_index("ix_action_rule_set_status")

    op.drop_table("action_rule_set")
    # ### end Alembic commands ###
