"""add industry_event table

Revision ID: 37233a8e9b66
Revises: 2827d9120b33
Create Date: 2026-09-13 20:07:50.519096

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

import intelligence.types  # custom column types (GUID / JSONB / UTCDateTime) used across the schema


revision: str = "37233a8e9b66"
down_revision: str | None = "2827d9120b33"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "industry_event",
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("city", sa.String(length=120), nullable=False),
        sa.Column("country", sa.String(length=120), nullable=False),
        sa.Column("venue", sa.String(length=300), nullable=True),
        sa.Column("starts_at", intelligence.types.UTCDateTime(), nullable=False),
        sa.Column("ends_at", intelligence.types.UTCDateTime(), nullable=True),
        sa.Column("topics", intelligence.types.JSONB(), nullable=False),
        sa.Column("source_url", sa.String(length=1024), nullable=False),
        sa.Column("source_label", sa.String(length=200), nullable=False),
        sa.Column("retrieved_at", intelligence.types.UTCDateTime(), nullable=False),
        sa.Column("added_by", sa.String(length=120), nullable=False),
        sa.Column("id", intelligence.types.GUID(), nullable=False),
        sa.Column(
            "created_at",
            intelligence.types.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("industry_event")
    # ### end Alembic commands ###
